name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update system
      run: sudo apt update -y
    - name: Install libev
      run: sudo apt install -y libev4 libev-dev
    - name: Install systemd
      run: sudo apt install -y libsystemd-dev
    - name: Install rst2man
      run: sudo apt install -y python3-docutils
    - name: Install zstd
      run: sudo apt install -y libzstd-dev
    - name: Install lz4
      run: sudo apt install -y liblz4-dev
    - name: Install libssh
      run: sudo apt install -y libssh-dev
    - name: Install libarchive
      run: sudo apt install -y libarchive-dev
    - name: Install libcurl
      run: sudo apt install -y libcurl4-nss-dev
    - name: Install clang
      run: sudo apt install -y clang
    - name: Install cJSON
      run: sudo apt install -y libcjson-dev
    - name: GCC/mkdir
      run: mkdir build
      working-directory: /home/runner/work/pgmoneta/pgmoneta/
    - name: GCC/cmake
      run: export CC=/usr/bin/gcc && cmake -DCMAKE_BUILD_TYPE=Debug ..
      working-directory: /home/runner/work/pgmoneta/pgmoneta/build/
    - name: GCC/make
      run: make
      working-directory: /home/runner/work/pgmoneta/pgmoneta/build/
    - name: rm -Rf
      run: rm -Rf build/
      working-directory: /home/runner/work/pgmoneta/pgmoneta/
    - name: CLANG/mkdir
      run: mkdir build
      working-directory: /home/runner/work/pgmoneta/pgmoneta/
    - name: CLANG/cmake
      run: export CC=/usr/bin/clang && cmake -DCMAKE_BUILD_TYPE=Debug ..
      working-directory: /home/runner/work/pgmoneta/pgmoneta/build/
    - name: CLANG/make
      run: make
      working-directory: /home/runner/work/pgmoneta/pgmoneta/build/
  


  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: Update system
      run: brew update
    - name: Install libev
      run: brew install libev
    - name: Install rst2man
      run: brew install docutils
    - name: Install libarchive
      run: brew install --ignore-dependencies libarchive
    - name: Install clang
      run: brew install llvm
    - name: Install cJSON
      run: brew install cjson
    - name: GCC/mkdir
      run: mkdir build
      working-directory: /Users/runner/work/pgmoneta/pgmoneta/
    - name: GCC/cmake
      run: export CC=/usr/bin/gcc && cmake -DCMAKE_BUILD_TYPE=Debug ..
      working-directory: /Users/runner/work/pgmoneta/pgmoneta/build/
    - name: GCC/make
      run: make
      working-directory: /Users/runner/work/pgmoneta/pgmoneta/build/
    - name: rm -Rf
      run: rm -Rf build/
      working-directory: /Users/runner/work/pgmoneta/pgmoneta/
    - name: CLANG/mkdir
      run: mkdir build
      working-directory: /Users/runner/work/pgmoneta/pgmoneta/
    - name: CLANG/cmake
      run: export CC=/usr/bin/clang && cmake -DCMAKE_BUILD_TYPE=Debug ..
      working-directory: /Users/runner/work/pgmoneta/pgmoneta/build/
    - name: CLANG/make
      run: make
      working-directory: /Users/runner/work/pgmoneta/pgmoneta/build/
